### ISSUE TITLE
Will there be an option for "prune" option of the compiler?

### ISSUE THREAD

**Issue by Danon** [xp-framework/compiler#119]
For example, if I use typed properties, `private string $field`, would there be an option to simply transpile it to `private $field`, without implementing the check? Like a `light` version? And any kid of PHP "feature", would simply be replaced by similar implementation without the polyfills?

Or it's something you'd prefer not do do?

**Comment by thekid** [comment]
Something I've also been thinking about, especially when working on #118, which now generates a __get / __set combination to implement type-checking. PHP itself doesn't have a version of types to denote *syntax only, do not check at runtime*, as this is what people typically do by using apidocs. Still, for consistency, we might want to have syntactic support for this.

Here are some ideas:

```php
// 1 - Use square braces - like optional notation in most Un*x command line tools' help
function fixture([string] $type) { ... }

// 2 - Use @ as prefix for the type, reminds of the error suppression operator, but also of apidoc
function fixture(@string $type) { ... }

// 3 - Use type unions essentially evaluating to no type-checking, the compiler could then omit this
function fixture(mixed|string $type) { ... }

// 4 - Use ? as suffix - putting the type in question (might be confused for ?string, which is nullable!)
function fixture(string? $type) { ... }

// 5 - Use ?? as suffix - the null-coalesce operator (might look weird in conjunction will nullable types)
function fixture(string?? $type) { ... }

// 6 - Use special comments
function fixture(/* unchecked */ string $type) { ... }

// 7 - Use special attribute from the lang package
function fixture(#[Unchecked] string $type) { ... }
```

I currently favor the attribute approach, as it's syntactially compatible *and* would fall nicely in line with other attributes that could trigger compiler actions, like `#[Deprecated]`.

**Comment by thekid** [comment]
Another thought may be go for an even more generic annotation with https://wiki.php.net/rfc/internal_method_return_types merged to PHP 8.1. This change produces these kinds of errors with method signatures:

![image](https://user-images.githubusercontent.com/696742/126906724-e83fde3f-d0cd-4cd3-adeb-c676e6770b6c.png)

While in this case we can simply add `Traversable` as return type in all PHP versions, it doesn't work without breaking PHP 7 for the `ArrayAccess` methods - see https://github.com/xp-framework/core/issues/276

```php
// Correct for PHP 8.1, searches for a type named "void" in PHP 7.0
function offsetSet($offset, $value): void { ... }

// Only emit "void" for PHP 8.1+, uses version_compare() syntax
#[Checked('>=8.1.0')]
function offsetSet($offset, $value): void { ... }

// Never emit type
#[Checked(null)]
function fixture($type) { ... }
```

*For parameters, we'd use parameter annotations*

**Comment by thekid** [comment]
One idea that came to my mind is to be able to customize the emitter by adding and/or removing traits from it, thus overriding or revealing the default behavior, respectively.

```bash
$ xp compile +OmitPropertyTypes <in> <out>
```

**Comment by thekid** [comment]
Settled for the following:

* The default is to omit property type checks for PHP < 7.4
* Using `xp compile -t php:7.0 -e php:virtual-property-types <in> <out>`, code can be emitted that will generate type checks

The reason not to enable this emitter by default is that a) it doesn't work for static properties due to a limitation in PHP and b) the generated code is *much* slower than the native implementation - see #129.

**Comment by thekid** [comment]
```php
// 2 - Use @ as prefix for the type, reminds of the error suppression operator, but also of apidoc
function fixture(@string $type) { ... 
```

See https://docs.hhvm.com/hack/types/soft-types - should we reconsider?

**Comment by Danon** [comment]
My original idea behind this issue was to keep the source code intact, and only decide whether we want to add additional runtime checking at the stage of compilation (to leave them off or try and backport them).

**Comment by thekid** [comment]
> and only decide whether we want to add additional runtime checking at the stage of compilation

@Danon - have a look at #158, would that meet your needs?
